"""phase 1 schema: media_item, library_entry, series_progress, recommendation_session, taste_profile

Revision ID: 50d4f647d8db
Revises: 
Create Date: 2026-08-31 18:06:26.368057
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '50d4f647d8db'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('tmdb', 'open_library', 'google_books', name='media_source'), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('movie', 'series', 'book', name='media_type'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('external_rating', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('artwork_url', sa.Text(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('seasons', sa.Integer(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('episode_runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('mood_tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_media_item_source_source_id')
    )
    op.create_table('recommendation_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_request', sa.Text(), nullable=False),
    sa.Column('preference_object', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('clarification_question', sa.Text(), nullable=True),
    sa.Column('clarification_answer', sa.Text(), nullable=True),
    sa.Column('clarification_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('state', sa.Enum('extracting', 'needs_clarification', 'awaiting_answer', 'ranking', 'results', 'error', name='session_state'), server_default='extracting', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taste_profile',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('favourite_genres', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('favourite_languages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('avg_rating_by_genre', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('avg_rating_by_language', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('completion_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('completion_rate_by_genre', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('drop_patterns', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_item_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('want', 'in_progress', 'completed', 'dropped', name='library_status'), nullable=False),
    sa.Column('favourite', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1.0 AND rating <= 10.0 AND (rating * 2) = floor(rating * 2))', name='ck_library_entry_rating_half_step'),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_item_id', name='uq_library_entry_media_item')
    )
    op.create_table('series_progress',
    sa.Column('library_entry_id', sa.UUID(), nullable=False),
    sa.Column('seasons_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_season', sa.Integer(), nullable=True),
    sa.Column('current_episode', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_entry_id'], ['library_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('library_entry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('series_progress')
    op.drop_table('library_entry')
    op.drop_table('taste_profile')
    op.drop_table('recommendation_session')
    op.drop_table('media_item')
    # ### end Alembic commands ###
    # Enum types are created implicitly by create_table; drop them explicitly so
    # a downgrade/upgrade cycle stays clean.
    for enum_name in (
        "media_source",
        "media_type",
        "session_state",
        "library_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
