"""add season_episode_counts to media_item

Revision ID: 655ccfa5f7f8
Revises: 50d4f647d8db
Create Date: 2026-09-07 22:45:00.489138
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '655ccfa5f7f8'
down_revision: Union[str, None] = '50d4f647d8db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_item', sa.Column('season_episode_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_item', 'season_episode_counts')
    # ### end Alembic commands ###
